name: Link Checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          args: --base . --verbose --no-progress './**/*.md' './**/*.mdx' './**/*.html' './**/*.rst'
